#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${DIR}/../lib/shared.bash"

if [[ "$(plugin_read_config DEBUG false)" =~ ^(true|on|1)$ ]]; then
  set -x
fi

# Exit early if no download projects configured
if [[ -z "${BUILDKITE_PLUGIN_QDB_ARTIFACTS_DOWNLOAD_PROJECTS_0_VARIANT:-}" ]]; then
  exit 0
fi

echo "~~~ :arrow_down: Downloading artifacts"

run_artifacts_py download

